<a href="https://colab.research.google.com/github/aryanSmalhotra/AIML/blob/main/Week2AIML_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_str=["Iphone","Pixel","Redmi","Samsung","LG"]
arr_num=[4,6,7,3,8]

In [ ]:
#numpy arrays
np_arr_str=np.array(arr_str)
np_arr_num=np.array(arr_num)

print("Numpy Array:",np_arr_str)
print("Numpy Array:",np_arr_num)

Numpy Array: ['Iphone' 'Pixel' 'Redmi' 'Samsung' 'LG']
Numpy Array: [4 6 7 3 8]


In [ ]:
#numpy arrays data type
print("Type Numpy Array:",type(np_arr_str))
print("Type Numpy Array:",type(np_arr_num))

#normal arrays data type
print("Type Normal Array:",type(arr_str))
print("Type Normal Array:",type(arr_num))



Type Numpy Array: <class 'numpy.ndarray'>
Type Numpy Array: <class 'numpy.ndarray'>
Type Normal Array: <class 'list'>
Type Normal Array: <class 'list'>


In [ ]:
#matix array
matrix=np.array([[9,8,6],[4,2,8],[1,7,5]])
print(matrix)

[[9 8 6]
 [4 2 8]
 [1 7 5]]


In [ ]:
#data type of matrix array
print("data type of matrix",type(matrix))

data type of matrix <class 'numpy.ndarray'>


In [ ]:
#numpy arange functions

arr2=np.arange(start=0,stop=10)
print(arr2)

#short way
arr3=np.arange(0,10)
print(arr3)

#adding a step of size 5
arr_step=np.arange(0,21,5)
print(arr_step)



[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 0  5 10 15 20]


In [ ]:
#linspace func

matrix2=np.linspace(10,20,10)
matrix2



array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [ ]:
#matix ones

matrix_ones=np.ones([3,5])


#matrix zeros

matrix_zero=np.zeros([3,5])



#matrix eye

matrix_eye=np.eye(5)

print(matrix_ones,matrix_zero,matrix_eye)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
#NumPY Reshape

arr4=np.arange(0,25)

arr_reshape=arr4.reshape((5,5))
arr_reshape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
#sin #cos #tan

print(np.sin(4))

print(np.cos(6))

print(np.tan(8))

-0.11478481378318722
0.9933903797222716
-0.11554854579453279


In [ ]:
np.log(256)

5.545177444479562

In [ ]:
#Basic Algoriths

arr8=np.arange(3,8)

arr9=np.arange(1,6)

print("Addition:", arr8+arr9)
print("Subtraction:", arr8-arr9)
print(arr8*arr9)
print(arr8/arr9)
print("power",arr8**arr9)
print("inverse",1/arr8)



Addition: [ 4  6  8 10 12]
Subtraction: [2 2 2 2 2]
[ 3  8 15 24 35]
[3.         2.         1.66666667 1.5        1.4       ]
power [    3    16   125  1296 16807]
inverse [0.33333333 0.25       0.2        0.16666667 0.14285714]
